apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: klage-oppgave-consumer
  namespace: klage
  labels:
    team: klage
spec:
  image: {{image}}
  gcp:
    sqlInstances:
      - name: klage-oppgave-broker
        type: POSTGRES_12
        maintenanceWindow:
          day: 1
          hour: 4
        tier: {{ db_tier }}
        diskType: SSD
        highAvailability: {{ db_ha }}
        diskSize: {{ db_size }}
        diskAutoresize: true
        autoBackupTime: "02:00"
        cascadingDelete: false
        databases:
          - name: klage-oppgave-broker
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  port: 7088
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  ingresses:
    - {{ingress}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/prometheus
  secureLogs:
    enabled: true
  webproxy: true
  accessPolicy:
    outbound:
      rules:
        - application: klage-oppgave-api
  envFrom:
    - secret: srvklage-saksbeh
    - secret: oppgave-apikey
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
